@startuml
!include ..\..\..\..\..\..\/Skin.iuml
state "ACTION_STATE Broker Report to RTTM" as Broker_Report_to_RTTM <<ACTION>>
state "ACTION_STATE Post Trade Notification" as Post_Trade_Notification <<ACTION>>
state "WAIT_STATE Verbal Execution of Trade" as Verbal_Execution_of_Trade <<WAIT>>
state "ACTION_STATE Enter Broker Trade" as Enter_Broker_Trade <<ACTION>>
[*] --> Verbal_Execution_of_Trade
Verbal_Execution_of_Trade --> Enter_Broker_Trade : MESSAGE NewBrokerTrade
Enter_Broker_Trade --> Post_Trade_Notification
Post_Trade_Notification --> Broker_Report_to_RTTM
Broker_Report_to_RTTM --> [*]
@enduml
