@startuml
!include ../../..//Skin.iuml
state "ACTION_STATE Broker Report to RTTM" as Broker_Report_to_RTTM <<ACTION>>
state "WAIT_STATE Post Trade Notification" as Post_Trade_Notification <<WAIT>>
state "WAIT_STATE Verbal Execution of Trade" as Verbal_Execution_of_Trade <<WAIT>>
state "WAIT_STATE Enter Broker Trade" as Enter_Broker_Trade <<WAIT>>
[*] --> Verbal_Execution_of_Trade
Verbal_Execution_of_Trade --> Enter_Broker_Trade : MESSAGE NewBrokerTrade
Enter_Broker_Trade --> Post_Trade_Notification : MESSAGE NewBrokerTrade
Post_Trade_Notification --> Broker_Report_to_RTTM : MESSAGE NewBrokerTrade
Broker_Report_to_RTTM --> [*]
@enduml
