@startuml
!include ../../..//Skin.iuml
state "ACTION_STATE No Match" as No_Match <<ACTION>>
state "WAIT_STATE Match Incoming Firm Trade" as Match_Incoming_Firm_Trade <<WAIT>>
state "ACTION_STATE Trade is Matched" as Trade_is_Matched <<ACTION>>
state "WAIT_STATE Match Incoming Broker Trade" as Match_Incoming_Broker_Trade <<WAIT>>
state "WAIT_STATE Matching Trades" as Matching_Trades <<WAIT>>
[*] --> Matching_Trades
Matching_Trades --> Match_Incoming_Firm_Trade : MESSAGE IncomingFirmTrade
Match_Incoming_Firm_Trade --> Trade_is_Matched : MESSAGE TradeMatchFound
Trade_is_Matched --> [*]
Match_Incoming_Firm_Trade --> No_Match : MESSAGE NoTradeMatch
No_Match --> Matching_Trades
Matching_Trades --> Match_Incoming_Broker_Trade : MESSAGE IncomingBrokerTrade
Match_Incoming_Broker_Trade --> Trade_is_Matched : MESSAGE TradeMatchFound
Match_Incoming_Broker_Trade --> No_Match : MESSAGE NoTradeMatch
@enduml
