@startuml
!include Skin.iuml
state "Level 1" as Level_1 {
state "Level 2" as Level_2 {
state "Level 3" as Level_3 {
state "ACTION_STATE Level3b" as Level3b <<ACTION>>
state "WAIT_STATE Level3a" as Level3a <<WAIT>>
[*] --> Level3a
Level3a --> Level3b : MESSAGE Advance
Level3b --> [*]
}
[*] --> Level_3
Level_3 --> [*]
}
[*] --> Level_2
Level_2 --> [*]
}
[*] --> Level_1
Level_1 --> [*]
@enduml
