@startuml
!include Skin.iuml
state "WAIT_STATE State 3" as State_3 <<WAIT>>
state "WAIT_STATE State 5" as State_5 <<WAIT>>
state "Composite 1" as Composite_1 {
state "ACTION_STATE State 2" as State_2 <<ACTION>>
state "WAIT_STATE State 1" as State_1 <<WAIT>>
[*] --> State_1 : MESSAGE Advance
State_1 --> State_2 : MESSAGE Advance
State_2 --> [*]
}
state "WAIT_STATE State 4" as State_4 <<WAIT>>
state "Composite 6" as Composite_6 {
state "ACTION_STATE State 7" as State_7 <<ACTION>>
[*] --> State_7 : MESSAGE Advance
State_7 --> [*]
}
[*] --> Composite_1 : MESSAGE Advance
Composite_1 --> State_3
State_3 --> State_4 : MESSAGE Advance
State_4 --> State_5 : MESSAGE Advance
State_5 --> Composite_6 : MESSAGE Advance
Composite_6 --> [*]
@enduml
