@startuml
!include Skin.iuml
state "WAIT_STATE State 3" as State_3 <<WAIT>>
state "WAIT_STATE State 2" as State_2 <<WAIT>>
state "ACTION_STATE State 4" as State_4 <<ACTION>>
state "ACTION_STATE State 1" as State_1 <<ACTION>>
[*] --> State_1 : MESSAGE Advance
State_1 --> State_2
State_2 --> State_3 : MESSAGE PrivateMessage
State_3 --> State_4 : MESSAGE Advance
State_4 --> [*]
@enduml
